trigger: []

name: Build and Deploy

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscriptionEndpoint: 'Azure subscription 1 (4effccd0-b865-4ccc-8676-7b920f901b89)'
  webAppName: 'TestCaclulatorSolution'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        installationScript: 'install'
        installationVersion: '7.x'
    - script: dotnet build ./BlazorServerTest
      displayName: 'dotnet build'
    - script: dotnet publish ./BlazorServerTest -c Release -o $(Build.ArtifactStagingDirectory)
      displayName: 'dotnet publish'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        installationScript: 'install'
        installationVersion: '7.x'
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureSubscriptionEndpoint)
        appName: $(webAppName)
        package: $(Pipeline.Workspace)/drop/**/*.zip