trigger:
- '*'  # This will trigger the pipeline on every push to any branch

pr:
- '*'  # This will also trigger the pipeline on pull requests

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  steps:
  - script: echo 'Build and deploy steps go here'
    displayName: 'Build and Deploy'