trigger:
  branches:
    include:
      - master

name: '$(SourceBranchName)_$(Rev:rr)'

pool:
  vmImage: 'windows-latest'

variables:
  azureSubscriptionEndpoint: 'Azure subscription 1 (4effccd0-b865-4ccc-8676-7b920f901b89)'
  webAppName: 'TestCaclulatorSolution'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        installationPath: $(Agent.ToolsDirectory)/dotnet
        installationScript: 'install'
        installationVersion: '7.x'

    - script: |
        echo List of Folders in Current Working Directory:
        dir /B /AD
      displayName: 'List Folders'

    - script: |
        cd BlazorServerTest
        echo List of Folders in Current Working Directory:
        dir /B /AD
      displayName: 'List Folders Inside Released Path'

    - script: dotnet build
      displayName: 'Build ASP.NET App'
      workingDirectory: $(System.DefaultWorkingDirectory)/BlazorServerTest  # Set the correct path to your project
      failOnStderr: true

    - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory) --no-restore BlazorServerTest/BlazorServerTest.csproj -maxcpucount:4
      displayName: 'dotnet publish'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
