name: Azure Deployment

on:
  push:
    branches:
      - main
      - development
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Adjust to your desired version

      - name: Build and test
        run: |
          cd src/BlazorServerTest
          dotnet build
          dotnet test