name: Azure Deployment

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on every branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Adjust to your desired version

      - name: Build and test
        run: |
          dotnet build
          dotnet test

      - name: Publish Artifact
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

      #- name: Deploy to Azure
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: TestCaclulatorSolution  # Replace with your Azure App Service name
      #    slot-name: production
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TestCaclulatorSolution'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbd79b749d9e45069d3086c20c30017a }}
          package: .