name: Azure Deployment

on:
  push:
    branches:
      - '*'  # This will trigger the workflow on every branch push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Adjust to your desired version

      - name: Build and test
        run: |
          dotnet build
          dotnet test
