name: Azure Deployment

on:
  push:
    branches:
      - main
      - development
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x  # Adjust to your desired version

      - name: Build and test
        run: |
          cd BlazorServerTest
          dotnet build
          dotnet test

      #- name: Publish Artifact
      #  run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/BlazorServerTest
      #
      #- name: Upload artifact for deployment job
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: .net-app
      #    path: ${{ github.workspace }}/BlazorServerTest
      #
      #- name: Deploy to Azure
      #  uses: azure/webapps-deploy@v2
      #  with:
      #    app-name: TestCaclulatorSolution  # Replace with your Azure App Service name
      #    slot-name: production
      #    publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #    package: ./publish

  deploy-using-azure-pipelines:
    runs-on: ubuntu-latest
    needs: build

    steps:
      #- name: Download artifact from build job
      #  uses: actions/download-artifact@v2
      #  with:
      #    name: .net-app

      - name: Trigger an Azure Pipeline
        id: deploy-to-webapp
        uses: Azure/pipelines@releases/v1
        with:
            azure-devops-project-url: 'https://dev.azure.com/genresal/genresal'
            azure-pipeline-name: 'WebApp_Azure_Prod' 
            azure-devops-token: '${{ secrets.AZURE_PIPELINE_TOKEN }}'